"""added books, user books, and club books plus relationships

Revision ID: cdec4a8a118d
Revises: bb1e78cd8e80
Create Date: 2023-12-19 00:57:36.603771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdec4a8a118d'
down_revision = 'bb1e78cd8e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('cover_i', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_status', sa.Enum('read', 'reading', 'want to read'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_user_books_book_id_books')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_books_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_books_user_id'), ['user_id'], unique=False)

    op.create_table('book_clubs_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_club_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('currently_reading', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['book_club_id'], ['book_clubs.id'], name=op.f('fk_book_clubs_books_book_club_id_book_clubs')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_clubs_books_book_id_books')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_clubs_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_clubs_books_book_club_id'), ['book_club_id'], unique=False)

    with op.batch_alter_table('book_clubs_users', schema=None) as batch_op:
        batch_op.drop_index('ix_book_clubs_users_book_club_id')
        batch_op.create_index(batch_op.f('ix_book_clubs_users_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_clubs_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_clubs_users_user_id'))
        batch_op.create_index('ix_book_clubs_users_book_club_id', ['book_club_id'], unique=False)

    with op.batch_alter_table('book_clubs_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_clubs_books_book_club_id'))

    op.drop_table('book_clubs_books')
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_books_user_id'))

    op.drop_table('user_books')
    op.drop_table('books')
    # ### end Alembic commands ###
